version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.dockerfile
    ports:
      - "8081:80"
      - "9003:9000"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: docker/php.dockerfile
    volumes:
      - .:/var/www/html
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal

  mysql:
    image: mysql:latest
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8082:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  composer:
    image: composer
    container_name: composer-container
    volumes:
      - .:/var/www/html
    command: "composer install --no-scripts --no-autoloader && composer dump-autoload --no-scripts --no-dev --optimize"
